export const DEFAULT_GAMES = [
  {
    name: 'Valorant',
    short_name: 'VAL',
    stat_fields: [
      { key: 'rating', label: 'Rating', type: 'number' },
      { key: 'acs', label: 'ACS', type: 'number' },
      { key: 'kd_ratio', label: 'K/D Ratio', type: 'number' },
      { key: 'headshot_pct', label: 'Headshot %', type: 'percentage' },
      { key: 'first_kills', label: 'First Kills/Round', type: 'number' },
      { key: 'clutch_pct', label: 'Clutch %', type: 'percentage' },
      { key: 'rank', label: 'Rank', type: 'rank' },
    ],
    role_options: ['Duelist', 'Initiator', 'Controller', 'Sentinel', 'Flex'],
  },
  {
    name: 'League of Legends',
    short_name: 'LOL',
    stat_fields: [
      { key: 'lp', label: 'LP', type: 'number' },
      { key: 'win_rate', label: 'Win Rate', type: 'percentage' },
      { key: 'kda', label: 'KDA', type: 'number' },
      { key: 'cs_per_min', label: 'CS/Min', type: 'number' },
      { key: 'vision_score', label: 'Vision Score', type: 'number' },
      { key: 'rank', label: 'Rank', type: 'rank' },
    ],
    role_options: ['Top', 'Jungle', 'Mid', 'ADC', 'Support', 'Fill'],
  },
  {
    name: 'CS2',
    short_name: 'CS2',
    stat_fields: [
      { key: 'rating', label: 'HLTV Rating', type: 'number' },
      { key: 'adr', label: 'ADR', type: 'number' },
      { key: 'kd_ratio', label: 'K/D Ratio', type: 'number' },
      { key: 'headshot_pct', label: 'Headshot %', type: 'percentage' },
      { key: 'opening_kills', label: 'Opening Kills/Round', type: 'number' },
      { key: 'clutch_pct', label: 'Clutch %', type: 'percentage' },
      { key: 'rank', label: 'Rank', type: 'rank' },
    ],
    role_options: ['Rifler', 'AWPer', 'Entry', 'Lurker', 'IGL', 'Support'],
  },
  {
    name: 'Fortnite',
    short_name: 'FN',
    stat_fields: [
      { key: 'pr', label: 'PR Points', type: 'number' },
      { key: 'earnings', label: 'Earnings ($)', type: 'number' },
      { key: 'win_rate', label: 'Win Rate', type: 'percentage' },
      { key: 'kd_ratio', label: 'K/D Ratio', type: 'number' },
      { key: 'avg_placement', label: 'Avg Placement', type: 'number' },
      { key: 'builds_per_min', label: 'Builds/Min', type: 'number' },
    ],
    role_options: ['Solo', 'Duo', 'Trio', 'Squad', 'IGL', 'Fragger', 'Support'],
  },
  {
    name: 'Rocket League',
    short_name: 'RL',
    stat_fields: [
      { key: 'mmr', label: 'MMR', type: 'number' },
      { key: 'goals_per_game', label: 'Goals/Game', type: 'number' },
      { key: 'assists_per_game', label: 'Assists/Game', type: 'number' },
      { key: 'saves_per_game', label: 'Saves/Game', type: 'number' },
      { key: 'shooting_pct', label: 'Shooting %', type: 'percentage' },
      { key: 'rank', label: 'Rank', type: 'rank' },
    ],
    role_options: ['Striker', 'Midfield', 'Defender', 'Flex'],
  },
  {
    name: 'Call of Duty',
    short_name: 'COD',
    stat_fields: [
      { key: 'kd_ratio', label: 'K/D Ratio', type: 'number' },
      { key: 'spm', label: 'Score/Min', type: 'number' },
      { key: 'accuracy', label: 'Accuracy %', type: 'percentage' },
      { key: 'win_rate', label: 'Win Rate', type: 'percentage' },
      { key: 'hardpoint_time', label: 'HP Time (s)', type: 'number' },
      { key: 'snd_first_bloods', label: 'SnD First Bloods', type: 'number' },
    ],
    role_options: ['Slayer', 'OBJ', 'Flex', 'AR', 'SMG'],
  },
  {
    name: 'Apex Legends',
    short_name: 'APEX',
    stat_fields: [
      { key: 'damage_per_game', label: 'Damage/Game', type: 'number' },
      { key: 'kd_ratio', label: 'K/D Ratio', type: 'number' },
      { key: 'win_rate', label: 'Win Rate', type: 'percentage' },
      { key: 'headshot_pct', label: 'Headshot %', type: 'percentage' },
      { key: 'avg_placement', label: 'Avg Placement', type: 'number' },
      { key: 'rank', label: 'Rank', type: 'rank' },
    ],
    role_options: ['IGL', 'Fragger', 'Support', 'Flex'],
  },
]
